#!/usr/bin/env python3

# File: code/logic.py

"""
Provides the core (business) logic.
"Controller" in MCV.
Supported by routines in:
    code/applicants.py
    code/people.py

getters: person, sponsor, ...
putters: person, applicant, 
"""

from pathlib import Path
try: import letters  # letter writing module
except ImportError: from code import letters

try: import data  # interaction with database
except ImportError: from code import data

try: from code import helpers
except ImportError: import helpers

try: import cli as ui
except ImportError: from code import cli as ui
try: import people
except ImportError: from code import people
try: import applicants
except ImportError: from code import applicants

#print("logic.py: being imported (or run.)")

dues = 200

def _collect(func, mapping, f_name, header):
    """
    ## NOT USED!!!  ##
    Provides choice to 
        1. send a mapping to _or_
        2. retrieve data from a json file 
    Returns a dict either ...
    1. json.loaded from <f_name> or 
    2. generated by <func>(<mapping>)
    Does _not_ change the data base!
    """
    file_path = Path(f_name)
    if file_path.is_file():
        choice = ui.choose(
                ["Pick from file", "Collect info"],
                header=header)
        if choice == "Pick from file":
            return helpers.load_json_file(
                    f_name)
    ret = func(mapping)
    helpers.dump2json(ret, f_name)
    return ret

def ck_collect():
    """ INCOMPLETE """
    d = dict(first= "George",
            last= "Smith",
            suffix= "",
            )
    mapping_f = 'temp.json'
    with open(mapping_f, 'r') as jf:
        pass

def ck_get_sponsors():
    for key, val in get_sponsors().items():
        print(f"{key}: {val}")

def ck_new_applicant():
    print("Running get_applicant.py")
    dest = "ck_app_entry.json"
    mapping = new_applicant()

    if mapping:
        with open(dest, 'w') as outf:
            json.dump(mapping, outf, indent=2)
        print("(Applicant) data dumped to "
                + f"{outf.name}")
        yn = input(
            "Print to screen as well? (yn): ")
        if yn and yn[0] in "yY":
            for key, val in mapping.items():
                print(f"{key}: {val}")
    else:
        print(f"new_applicant returned {mapping}")


def main():
    cmds_available = [
        people.get_person,
        applicants.get_sponsors,
        applicants.enter_applicant,
        applicants.update_applicant,
        ] 
    cmd = data.choose(cmds_available)  # may want to
        #  add default key word params header & text
    print()
    print(f"About to run {cmd.__name__} ...")
    res = cmd()
    print(f"Finished running {cmd.__name__} ==> ", end='')
    print(res)

def ck_get_person():
    ret = get_person()
    if ret:
        for key, value in ret.items():
            print(f"{key}: {value}")
    else:
        print(f"get_person returned {ret}")
    return ret

if __name__ == "__main__":
#   ck_new_applicant()
#   ck_get_sponsors()
#   print("running code/logic.py")
#   ck_get_person()
    main()

