#!/usr/bin/env python3

# File: code/logic.py

"""
Provides the core (business) logic.
"Controller" in MCV.
getters: person, sponsor, ...
putters: person, applicant, 
!!!!!!! Won't run !!!!!!!
Can be imported by main.py and tested that way.
"""

from pathlib import Path
try: import letters  # letter writing module
except ImportError: from code import letters

try: import data  # interaction with database
except ImportError: from code import data

try: from code import helpers
except ImportError: import helpers

try: import cli as ui
except ImportError: from code import cli as ui

#print("logic.py: being imported (or run.)")

ap_fee = 25
dues = 200
app_letters = "app_letters.txt"

def collect(func, mapping, f_name, header):
    """
    Returns a dict either ...
    1. json.loaded from <f_name> or 
    2. generated by <func>(<mapping>)
    If 2: the mapping is json loaded into <f_name>
    Does _not_ change the data base!
    """
    file_path = Path(f_name)
    if file_path.is_file():
        choice = ui.choose(
                ["Pick from file", "Collect info"],
                header=header)
        if choice == "Pick from file":
            return helpers.load_json_file(
                    f_name)
    ret = func(mapping)
    helpers.dump2json(ret, f_name)
    return ret

def ck_collect():
    d = dict(first= "George",
            last= "Smith",
            suffix= "",
            )
    mapping_f = 'temp.json'
    with open(mapping_f, 'r') as jf:
        pass

def getID():
    """
    Returns the last entered personID.
    Don't need a user interface version of this.
    """
    return data.get_highest_ID()

def get_person():
    """
    Method of selecting an entry (mapping)
    from the People table.
    """
    while True:
        hints = data.get_hints(
            header="People Table Lookup",
            text="Ener hints (no need for wild card)")
        choices = data.getP_from_clues(hints)
        choice = data.choose(choices,
            header="Choices",
            text="Select by number (0 to abort)..")
        if choice:
            if data.confirm_mapping(choice):
                return choice
        else:
            yn = data.yn(
                    header="Person not found...",
                    text="Try again? (yn): ")
            if not yn:
                return

def get_sponsors():
    """
    Returns a mapping of both sponsors
    with keys prefaced with "s1_" and "s2_"
    """
    while True:
        sponsors = []
        while len(sponsors)<2:
            data.announce(header="Need 2 sponsors..",
              text=f"Enter sponsor #{len(sponsors)+1}:")
            sponsor = get_person()
            if sponsor:
                pass
                sponsors.append(sponsor)
        for key, val in sponsors[0].items():
            ret0 = {f"s1_{key}": val for
                    key, val in sponsors[0].items()}
        for key, val in sponsors[1].items():
            k = f"s2_{key}"
            ret1 = {f"s2_{key}": val for
                    key, val in sponsors[1].items()}
        ret = ret0 | ret1
        res = dict(sorted(ret.items()))
        # emails provided by keys "s1_email" & "s2_email"
        return res

empty_dict = {}

def create_person(empty_dict):
    """
    Create an entry into the People table
    Return mapping with personID value.
    """
    keys = data.person_keys()
    mapping = {key: "" for key in keys}
    person = data.entries(mapping,
        header="Adding New Person to People Table",
        text="Add values (empty strings accepted)... ")
    if person:
        data.put_person(person)
        person["personID"] = getID()
        helpers.dump2json(person,
                          "A_new_person.json")
#       print("logic/create_person: person...")
#       for key, val in person.items:
#           print(f"{key}: {val}")
#       _ = input()
        return person
    else:
        print("logic/create_person: person is False")

def add_person_status(ap_mapping, statusID):
    data.set_person_status(ap_mapping["personID"],
           statusID,
           ap_mapping["fee_rcvd"])  # begin date

def in_good_standing(personID):
    return data.is_member_in_good_standing(personID)

def add_sponsors(applicant):
    """
    Adds sponsor data to applicant mapping.
    Also adds first 3 date keys all /w empty values
    Does _not_ change the data base!
    """
    sponsors = get_sponsors()
    ap_mapping = {
          "s1_ID": sponsors["s1_personID"],
          "s1_first": sponsors["s1_first"],
          "s1_last": sponsors["s1_last"],
          "s1_suffix": sponsors["s1_suffix"],
          "s2_ID": sponsors["s2_personID"],
          "s2_first": sponsors["s2_first"],
          "s2_last": sponsors["s2_last"],
          "s2_suffix": sponsors["s2_suffix"],
          "app_rcvd": "",
          "fee_rcvd": "",
          "meeting1": "",
                  }
    ret = applicant | ap_mapping
    return ret

def add_dates(applicant):
    """
    Add 0-3 of the Applicant table date entries.
    and on basis of them adds 
    Does _not_ change the data base!
    """
    ap_mapping = ui.add_info(applicant,
                "app_rcvd", "fee_rcvd", "meeting1",
                header="Applicant Dates",
                text="Add dates as appropriate:")
    if not (isinstance(applicant, dict) 
            and isinstance(ap_mapping, dict)):
        print("major problem in code/logic.add_dates")
    return applicant | ap_mapping

def load_applicant(applicant):
    """
    Applicant, Person_Status, +/- Receipts table entries.
    People table entry has already been done and key/value
    pairs assigned to <applicant>.
    """
    applicant = data.create_applicant_entry(applicant)
    applicant = data.create_person_status_entry(applicant)

def add_letter(mapping):
    f"""
    Generate or add to text file <app_letters>."
    Mapping must contain data needed.
    """
    print(add_letter.__doc__)
    data.add_letter(mapping)

def new_applicant():
    """
    Returns a mapping of all info needed
    to create an applicant and create
    the appropriate acknolwdgement letter/email.
    Also makes entries into the People, Applicant,
    Person_Status and Receipts tables via sql module.
    <applicant>: data for People table plus personID
    <ap_mapping>:
    """
    ## create People table entry & return mapping...
    applicant = collect(create_person, {},
            "A_new_person.json",
            "Collect or Retrieve from JSON")
    ## add sponsors & dates to <applicant> mapping...
    applicant = collect(add_sponsors, applicant,
            "B_sponsors_incl.json",
            "Add sponsors or get from file?")
#   print("in code/logic.new_applicant...")
#   for key, val in applicant.items():
#       if key[0] == "s":
#           print(f"{key}: {val}")
#   _ = input("...new_applicant returned the above.")
    applicant = collect(add_dates, applicant,
            "C_all_info.json",
            "Add 3 dates or get from file?")
    data.create_applicant_entry(applicant)
    applicant["app_fee"] = ap_fee
    data.create_app_receipts_entry(applicant)
    data.receipts_and_status_entries(applicant)
    add_letter(applicant)

    # Applicant table entry...

redacted = '''
#######################
    ### Need to make entry into Person_Status table ###
    # Letters assigned as category is determined...
    if ap_mapping["meeting1"]:
        ap_mapping["letter"] = letters.letter_bodies[
                "app_with_1st_meeting"]
        #!!!#("send fee and 1st meeting letter,")
        add_person_status(ap_mapping, 4)
    elif ap_mapping["fee_rcvd"]:
        # need to send acknowledgement letter
        # status is 2 until acknowledgement is sent
        # setting status '3|a0|No meetings yet'...
        ap_mapping["letter"] = letters.letter_bodies[
                "new_applicant_welcome"]
        add_person_status(ap_mapping, 3)
        # adding to receipts...
    elif ap_mapping["app_rcvd"]:
        # letter re app but no fee received
        ap_mapping["letter"] = letters.letter_bodies[
                "app_fee_pending"]
        add_person_status(ap_mapping, 1)
    return ap_mapping
    '''

def get_person_table_entry(personID):
    return data.get_app_info(personID)

def update_applicant(id_=None):
    """
    Provides for addition of dates to Applicant table
    and Status table updates
    If not <id_>, calls get_person to get an ID
    Returns None if fails to find an applicant.
    """
    # first must pick an applicant...
    if not id_: id_ = 0
    ap_map = {"personID": id_,
              "first": "",
              "last": "",
              "suffix": "",
              }
    appl = data.entries(ap_map,
        header="Pick Applicant:by ID or clues",
        text="If ID unknown, add name clues.")
    id_ = appl["personID"]
    if not id_:  # use pick person to get an ID
        rec = get_person()
        id_ = rec["personID"]
    if not id_: return
    mapping = get_person_table_entry(id_)
    ret = {}
    keys = ["A_personID", "A_first", "A_last", "A_suffix",
        "AP_meeting1", "AP_meeting2", "AP_meeting3",
        "AP_approved", "AP_dues_paid", "AP_notified", ]
    date_keys = keys[4:]
    date_slot = None
    for date_key in date_keys:
        if not mapping[date_key]:
            key2fill = date_key.split('_')[1]
            break
    header=f"{mapping['A_first']} {mapping['A_last']}"
    if mapping["A_suffix"]:
        header = header + mapping["A_suffix"]
    text="Enter date (yyyymmdd)"

    d = {f"{key2fill}": "",  }
    ret = data.entries(d, header=header, text=text)
    data.add_date(mapping["A_personID"],
                key2fill, ret[f"{key2fill}"])
    # now need to update Person_Status table
    # key2fill relationship to status mapping:
    key_status_mapping = { # entry to update:
            "meeting1":     3,  # no meetngs yet
            "meeting2":     4,  # attended 1 meeting
            "meeting3":     5,  # attended 2 meeting
            "AP_approved":  6,  # attended 3 meeting
            "AP_dues_paid": 7,  # approved
            "AP_notified":  8,  # dues_paid
            }


def main():
    cmds_available = [
        get_person,
        get_sponsors,
        enter_applicant,
        update_applicant,
        ] 
    cmd = data.choose(cmds_available)  # may want to
        #  add default key word params header & text
    print()
    print(f"About to run {cmd.__name__} ...")
    res = cmd()
    print(f"Finished running {cmd.__name__} ==> ", end='')
    print(res)

def ck_get_person():
    ret = get_person()
    if ret:
        for key, value in ret.items():
            print(f"{key}: {value}")
    else:
        print(f"get_person returned {ret}")
    return ret

def ck_get_sponsors():
    for key, val in get_sponsors().items():
        print(f"{key}: {val}")

def ck_new_applicant():
    print("Running get_applicant.py")
    dest = "ck_app_entry.json"
    mapping = new_applicant()

    if mapping:
        with open(dest, 'w') as outf:
            json.dump(mapping, outf, indent=2)
        print("(Applicant) data dumped to "
                + f"{outf.name}")
        yn = input(
            "Print to screen as well? (yn): ")
        if yn and yn[0] in "yY":
            for key, val in mapping.items():
                print(f"{key}: {val}")
    else:
        print(f"new_applicant returned {mapping}")

if __name__ == "__main__":
    pass
#   ck_new_applicant()
#   ck_get_sponsors()
#   print("running code/logic.py")
#   ck_get_person()
#   main()

